let body = JSON.parse($response.body);
if (body.features) {
    body.features = {
        "map.tracking.live": "enabled",
        "map.data.ads-b": "disabled",
        "map.data.mlat": "enabled",
        "map.data.faa": "enabled",
        "map.data.satellite": "enabled",
        "map.data.flarm": "enabled",
        "map.info.flight": "enabled",
        "map.info.aircraft": "enabled",
        "history.playback.global.days": 365,
        "history.flight.days": 365,
        "map.info.airport.onground.hours": 96,
        "map.labels.rows": 5,
        "map.filters.max": 50,
        "map.data.delaystats": "enabled",
        "map.view.fullscreen": "enabled",
        "adverts": "disabled",
        "map.timeout.mins": 30,
        "map.info.airport.arrivals": "enabled",
        "map.info.airport.departures": "enabled",
        "map.layer.waypoints": "enabled",
        "map.search": "enabled",
        "map.status.flight": "enabled",
        "map.layer.weather.volcano": "enabled",
        "map.view.multi": "enabled",
        "user.fleets.max": 50,
        "map.view.delay": "enabled",
        "history.aircraft.days": 365,
        "map.info.aircraft.registration": "enabled",
        "map.info.aircraft.type": "enabled",
        "map.info.aircraft.code": "enabled",
        "history.playback.flight.days": 365,
        "history.playback.days": 365,
        "map.info.flight.ground-speed": "enabled",
        "map.info.flight.calibrated-altitude": "enabled",
        "map.info.flight.track": "enabled",
        "map.info.flight.position": "enabled",
        "map.view.fleet.onground": 10,
        "user.fleets.max.aircraft": 1000,
        "map.view.3d.basic": 3,
        "map.widgets": 1,
        "map.widgets.last_clicked_flights": "enabled",
        "map.widgets.bookmarks": "enabled",
        "usage.rights": "Private",
        "map.widgets.bookmarks.max": 50
    };
}

if (body.userData) {
    body.userData.accountType = 'pre';
}

if (body.userData.features) {
    body.userData.features = {
        "map.tracking.live": "enabled",
        "map.data.ads-b": "disabled",
        "map.data.mlat": "enabled",
        "map.data.faa": "enabled",
        "map.data.satellite": "enabled",
        "map.data.flarm": "enabled",
        "map.info.flight": "enabled",
        "map.info.aircraft": "enabled",
        "history.playback.global.days": 365,
        "history.flight.days": 365,
        "map.info.airport.onground.hours": 96,
        "map.labels.rows": 5,
        "map.filters.max": 50,
        "map.data.delaystats": "enabled",
        "map.view.fullscreen": "enabled",
        "adverts": "disabled",
        "map.timeout.mins": 30,
        "map.info.airport.arrivals": "enabled",
        "map.info.airport.departures": "enabled",
        "map.layer.waypoints": "enabled",
        "map.search": "enabled",
        "map.status.flight": "enabled",
        "map.layer.weather.volcano": "enabled",
        "map.view.multi": "enabled",
        "user.fleets.max": 30,
        "map.view.delay": "enabled",
        "history.aircraft.days": 365,
        "map.info.aircraft.registration": "enabled",
        "map.info.aircraft.type": "enabled",
        "map.info.aircraft.code": "enabled",
        "history.playback.flight.days": 365,
        "history.playback.days": 365,
        "map.info.flight.ground-speed": "enabled",
        "map.info.flight.calibrated-altitude": "enabled",
        "map.info.flight.track": "enabled",
        "map.info.flight.position": "enabled",
        "map.view.fleet.onground": 10,
        "user.fleets.max.aircraft": 1000,
        "map.view.3d.basic": 3,
        "map.widgets": 1,
        "map.widgets.last_clicked_flights": "disabled",
        "map.widgets.bookmarks": "enabled",
        "usage.rights": "Private",
        "map.widgets.bookmarks.max": 50
    };
}

$done({ body: JSON.stringify(body) });