var obj = JSON.parse($response.body); 
obj['data']['official']['type'] = 1;
obj['data']['official']['desc'] = "超级管理员";
obj['data']['official']['role'] = 1;
obj['data']['official']['title'] = "管理员";
obj['data']['vip']['status'] = 1;
obj['data']['vip']['avatar_subscript'] = 1;
obj['data']['vip']['role'] = 1;
obj['data']['vip']['type'] = 3;
obj['data']['vip']['vip_pay_type'] = 1;
$done({body: JSON.stringify(obj)});