var obj = JSON.parse($response.body); 
obj['textnow_wireless_store_banner']['banner_enabled'] = 0;
//obj['android']['native_ads']['in_call']['enabled']  = false;
//obj['android']['native_ads']['conversation_list']['enabled']  = false;
obj['android']['native_ads'] = {};
obj['android']['promo_campaign_ad'] = {};
//obj['android']['native_ads']['outgoing_call_message']['enabled']  = false;
//obj['android']['native_ads']['enable_native_ads'] = false;
obj['ad'] = {};
//obj['ad']['native_ads']['conversation_list']['enabled']  = false;
//obj['ad']['native_ads']['in_call']['enabled']  = false;
//obj['ad']['native_ads']['outgoing_call_message']['enabled']  = false;
//obj['ad']['native_ads']['default_native_ad'] = {};
//obj['ad']['native_ads']['native_announcement'] = {};
//obj['ad']['native_ads']['jsdict'] = [];
//obj['ad']['enable_native_ads']= false;
$done({body: JSON.stringify(obj)});