var obj = JSON.parse($response.body);
obj['state'] = "PREMIUM_SUBSCRIPTION";
obj['show_ads'] = false;
obj['premium_calling'] = true;
obj['platform'] = "TN_IOS_PREMIUM";
obj['code'] = "10000";
obj['result']['state'] = "PREMIUM_SUBSCRIPTION";
obj['result']['show_ads'] = false;
obj['result']['premium_calling'] = true;
obj['result']['platform'] = "TN_IOS_PREMIUM";
obj['result']['code'] = "10000";
$done({body: JSON.stringify(obj)});