#!name= 哔哩哔哩
#!desc= 哔哩哔哩App去广告
#!system=ios

[Rule]
URL-REGEX,^https:\/\/ap(p|i)\.bilibili\.com\/(pgc\/season\/rank\/cn|x\/v2\/(dm\/ad|rank.*rid=(168|5)|dataflow\/report|search\/(defaultword|trending|recommend|resource)|splash)),REJECT

[MITM]
hostname = app.bilibili.com, api.bilibili.com, api.live.bilibili.com

[Script]
哔哩哔哩 = requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/XOS/Profiles/Her/Surge/Script/Bilibili.js,pattern=^https?:\/\/ap(i|p).(live.)?bilibili.com\/x(live)?\/(resource\/show\/tab|v2\/(reply\/main|view\/material|account\/(mine(\/ipad)?|teenagers\/status)|view|feed\/index|rank|channel\/region\/list)|app-room/v1/index/getInfoByRoom)\?access_key,type=http-response
