#!name=抖音
#!desc=去除抖音广告和水印。

[URL Rewrite]
^https://aweme-eagle(.*)\.snssdk\.com/aweme/v2/ https://aweme-eagle$1.snssdk.com/aweme/v1/ 302

[Script]
抖音 & TikTok = type=http-request,pattern=^https:\/\/.*\.(amemv|musical)\.(com|ly)\/aweme\/v.*\/(feed|post),requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/ByteDance/Aweme.js
抖音 & TikTok = type=http-response,pattern=^https:\/\/.*\.(amemv|musical)\.(com|ly)\/aweme\/v.*\/(feed|post),requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/ByteDance/Aweme.js

[MITM]
hostname = %APPEND% *.snssdk.com, *.amemv.com, *.musical.ly
