#!name=Cookie 获取
#!desc=签到脚本 Cookie 获取，请在使用后将其禁用，以免产生不必要的 MITM.
#!system=ios

[Script]

# > 微博超话获取Cookie
微博超话 = max-size=0,script-path=https://cdn.jsdelivr.net/gh/XOS/Config@Her/Surge/Script/get_cookie_surge.js,pattern=https:\/\/weibo\.com\/p\/aj\/general\/button\?ajwvr=6&api=http:\/\/i\.huati\.weibo\.com\/aj\/super\/checkin,type=http-request

# > 电信营业厅
电信营业厅 = script-path=https://cdn.jsdelivr.net/gh/chavyleung/scripts@master/10000/10000.cookie.js,type=http-request,pattern=^https:\/\/wapside.189.cn:9001\/api\/home\/homeInfo
10000.cookie.js = script-path=https://cdn.jsdelivr.net/gh/chavyleung/scripts@master/10000/10000.cookie.js,type=http-response,pattern=^https:\/\/wapside.189.cn:9001\/api\/home\/homeInfo

# > 网易云音乐
# 浏览器访问并登录: https://music.163.com/m/login
网易云音乐 = script-path=https://cdn.jsdelivr.net/gh/chavyleung/scripts@master/neteasemusic/neteasemusic.cookie.js,type=http-request,pattern=^https?:\/\/music\.163\.com\/?.?

# > bilibili
# 浏览器访问并登录: https://www.bilibili.com 或 https://live.bilibili.com 系统提示: `获取Cookie: 成功`
哔哩哔哩 = script-path=https://cdn.jsdelivr.net/gh/chavyleung/scripts@master/bilibili/bilibili.cookie.js,type=http-request,pattern=^https:\/\/(www|live)\.bilibili\.com\/?.?

# > 联通营业厅
# 打开 APP , 进入签到页面, 系统提示: `获取刷新链接: 成功`,然后手动签到 1 次
# 首页>天天抽奖, 系统提示 `2` 次: `获取Cookie: 成功 (登录抽奖)` 和 `获取Cookie: 成功 (抽奖次数)`
联通营业厅 = script-path=https://cdn.jsdelivr.net/gh/chavyleung/scripts@master/10010/10010.cookie.js,type=http-request,pattern=^https:\/\/act.10010.com\/SigninApp\/signin\/querySigninActivity.htm
10010.cookie.js = script-path=https://cdn.jsdelivr.net/gh/chavyleung/scripts@master/10010/10010.cookie.js,type=http-request,pattern=^https:\/\/act.10010.com\/SigninApp(.*?)\/signin\/daySign.do
10010.cookie.js = script-path=https://cdn.jsdelivr.net/gh/chavyleung/scripts@master/10010/10010.cookie.js,type=http-request,pattern=^https:\/\/m.client.10010.com\/dailylottery\/static\/(textdl\/userLogin|active\/findActivityInfo)

# > WPS
WPS = script-path=https://cdn.jsdelivr.net/gh/chavyleung/scripts@master/wps/wps.cookie.js,type=http-request,pattern=^https:\/\/zt.wps.cn\/2018\/docer_check_in\/api\/act_list
wps.cookie.js = script-path=https://cdn.jsdelivr.net/gh/chavyleung/scripts@master/wps/wps.cookie.js,type=http-request,pattern=^https:\/\/zt.wps.cn\/2018\/clock_in\/api\/sign_up

# > 微信小程序活动抽奖 (By @makexp & @zZPiglet)
# 打开微信小程序 进入"活动抽奖"，手动签到一次或点击"已签到"
微信小程序 = script-path=https://cdn.jsdelivr.net/gh/zZPiglet/Task@master/WeChatLottery/WeChatLottery_new.js,type=http-request,pattern=^https:\/\/api-hdcj\.9w9\.com\/v\d\/sign

# > 京东
# 浏览器登录 https://bean.m.jd.com 点击签到并且出现签到日历
京东 = script-path=https://cdn.jsdelivr.net/gh/NobyDa/Script@master/JD-DailyBonus/JD_DailyBonus.js,type=http-request,pattern=https:\/\/api\.m\.jd\.com\/client\.action.*functionId=signBean

# > 百度贴吧
# 先登录,浏览器访问一下: https://tieba.baidu.com 或者 https://tieba.baidu.com/index/
百度贴吧 = script-path=https://cdn.jsdelivr.net/gh/chavyleung/scripts@master/tieba/tieba.cookie.js,type=http-request,pattern=^https?:\/\/tieba\.baidu\.com\/?.?

# > 人人视频
人人影视 = script-path=https://cdn.jsdelivr.net/gh/chavyleung/scripts@master/rrtv/rrtv.cookie.js,type=http-request,pattern=^https:\/\/api\.rr\.tv\/user\/profile

[MITM]
hostname = %APPEND% wapside.189.cn:9001, weibo.com, music.163.com, *.bilibili.com, act.10010.com, m.client.10010.com, zt.wps.cn, api-hdcj.9w9.com, api.m.jd.com, tieba.baidu.com, api.rr.tv
