#!name= 微博广告
#!desc=移除微博 App 启动页广告和推荐页广告。
#!system=ios

[Script]
开屏 = requires-body=1,script-path=https://hub.nange.cn/Script/Weibo/Launch.js,type=http-response,pattern=^https?://(sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad.php|/wbapplua/wbpullad.lua)

时间轴 = type=http-response,requires-body=1,max-size=-1,pattern=^https?://m?api\.weibo\.c(n|om)/2/(statuses/(unread|extend|positives/get|(friends|video)(/|_)(mix)?timeline)|stories/(video_stream|home_list)|(groups|fangle)/timeline|profile/statuses|comments/build_comments|photo/recommend_list|service/picfeed|searchall|cardlist|page|!/photos/pic_recommend_status|video/tiny_stream_video_list),script-path=https://hub.nange.cn/Script/Weibo/Timeline.js

评论 = type=http-response,pattern=^https://api\.weibo\.cn/2/comments/build_comments\? requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Weibo/Comment.js

最新推荐 = type=http-response,pattern=^https://api\.weibo\.cn/2/statuses/(unread_hot_timeline)|(friends/timeline)\? requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Weibo/Status.js

发现热门 = type=http-response,pattern=^https://api\.weibo\.cn/2/cardlist\? requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Weibo/FindHot.js

[MITM]
hostname = %APPEND% *.uve.weibo.com, api.weibo.cn, mapi.weibo.com, storage.wax.weibo.com
