#!name=常用规则
#!desc=日用夜用

[General]
force-http-engine-hosts = *91*:8080, *my10api*:8080

[Rule]
# > Royal TSX
URL-REGEX,^https?:\/\/api\.royalapps\.com\/api\/UpdateCheck$,REJECT

[Header Rewrite]
# > 颇可
;^https?:\/\/[\w-]+\.poco\.cn header-replace User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36

# > 添加标记
;^https?://(?:\w+\.)*?((nan|cdn|nange|bk9|nangle|vmgirls|cloudimg|somecache|applecache)\.(?:com\.cn|cn|ink|ge|com|net))[\\\/]* header-add Visitor Surge

# > 更改 UA
;^https?://(?:\w+\.)*?((nan|cdn|nange|bk9|nangle|vmgirls|cloudimg|somecache|applecache)\.(?:com\.cn|cn|ink|ge|com|net))[\\\/]* header-replace User-Agent Surge

[URL Rewrite]
# > 知乎
^https?:\/\/link\.zhihu\.com\/\?target=(https?)?(%3A|:)?(\/\/|%2F%2F)?(.*?)(&source.*)?$ http://$4 302
# > 115
^https?:\/\/home\.115\.com\/go\?(https?:\/\/)?(.*) http://$2 302

[Script]
# > 该模块可解决iOS14或IPadOS14无法在移动端安装IPA的问题. 注: 需要使用Shu+捷径或Jsbox辅助安装.
IPA应用安装 = type=http-request,pattern=^https?:\/\/x.io/(install|download)(\/jsbox)?$,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Apple/iPA_Install.js

# > 人人视频 解锁AI原画 (by@george Jiang & R)
人人视频会员解锁 = requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Live/RRTV.js,type=http-response,pattern=^https?:\/\/api\.rr\.tv(\/user\/privilege\/list|\/ad\/getAll|\/rrtv-video\/v4plus\/season\/detail)

人人视频 = requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Live/RRSP.js,type=http-response,pattern=^https?:\/\/api\.rr\.tv\/watch\/v4\/priority_video_quality\/get_priority_video_quality_config\?

# > 韩剧TV解锁蓝光
韩剧TV = requires-body=1,script-path=https://hub.nange.cn/Script/Live/HanjuTV.js,type=http-response,pattern=^http:\/\/api\.hanju\.koudaibaobao\.com\/api\/series\/rslvV4

# > 咪咕视频
indexC = type=http-response,pattern=^https:\/\/.*\.miguvideo\.com\/ability\/.+\/indexContract\?,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/MiGu/indexC.js
Gateway = type=http-response,pattern=^http:\/\/.*\.miguvideo\.com\/gateway\/playurl\/.+\/play\/?,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/MiGu/PlayUrl.js
PlayUrl = type=http-response,pattern=^https:\/\/play\.miguvideo\.com\/playurl\/.+\/play\/playurl\?,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/MiGu/PlayUrl.js
manage = type=http-response,pattern=^https:\/\/app-sc\.miguvideo\.com\/app-management\/.+\/resolution\/?,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/MiGu/Manage.js
member = type=http-response,pattern=^https:\/\/.*\.miguvideo\.com\/ability\/.+\/member-info\?,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/MiGu/Member.js

# > 奈飞评分
奈飞评分 = script-path=https://hub.nange.cn/Script/Netflix/Rating.js,type=http-request,pattern=^https?://ios\.prod\.ftl\.netflix\.com/iosui/user/.+path=%5B%22videos%22%2C%\d+%22%2C%22summary%22%5D

奈飞评分 = requires-body=1,script-path=https://hub.nange.cn/Script/Netflix/Rating.js,type=http-response,pattern=^https?://ios\.prod\.ftl\.netflix\.com/iosui/user/.+path=%5B%22videos%22%2C%\d+%22%2C%22summary%22%5D

单集评分 = type=http-response,pattern=^https?://ios\.prod\.ftl\.netflix\.com/iosui/warmer/.+type=show-ath,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Netflix/RatingSeason.js

# > VSCO滤镜VIP
VSCO = type=http-response ^https?:\/\/(api\.revenuecat\.com\/v\d\/subscribers|vsco\.co\/api\/subscriptions\/\d\.\d\/user-subscriptions)\?, requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Photo/VSCO.js

# > Termius 解锁本地pro  (By Maasea)
Termius = requires-body=1,script-path=https://hub.nange.cn/Script/Dev/Termius.js,type=http-response,pattern=https:\/\/api\.termius\.com\/api\/v3\/bulk\/account\/

# > WorkingCopy.js
;WorkingCopy= requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Dev/WorkingCopy.js,script-update-interval=0,type=http-response,pattern=^https?:\/\/education\.github\.com\/api\/user$

# > Lightroom
Lightroom = type=http-response,pattern=^https?:\/\/photos\.adobe\.io\/v2\/accounts,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Adobe/Lightroom.js,script-update-interval=-1

# > Photoshop Express
Photoshop Express = type=http-response,pattern=^https?:\/\/lcs-mobile-cops\.adobe\.io\/mobile_profile,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Adobe/PhotoShopExpress.js,script-update-interval=0

# > CamScanner unlocks pro, Cloud scanning is not available.
CamScanner = type=http-response,pattern=https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\?,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Work/CamScanner.js,script-update-interval=0

# > Bear熊掌记 (By Miao Miao)
Bear 熊掌记 = requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Work/Bear.js,type=http-response,pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt

# > Buyhack
VerifyReceipt = requires-body=1,max-size=262144,script-path=https://hub.nange.cn/Script/Life/VerifyReceipt.js,script-update-interval=0,type=http-response,pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$

# > Peak 解锁Pro
Peak = requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Work/Peak.js,type=http-response,pattern=^https?:\/\/billing\.peakcloud\.org\/billing\/2\/user\/me?

# > TextNow
premium_state = type=http-response,pattern=^https?:\/\/api\.textnow\.me\/.+\/users\/.+\/premium_state\?,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/TextNow/State.js,script-update-interval=-1

blocks = type=http-response,pattern=^https:\/\/api\.textnow\.me\/.+\/blocks\?,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/TextNow/TextNow.js,script-update-interval=-1

subscription = type=http-response,pattern=^https:\/\/api\.textnow\.me\/.+\/users\/.+\/subscription\?,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/TextNow/State.js,script-update-interval=-1

subscription_state = type=http-response,pattern=^https:\/\/api\.textnow\.me\/.+/users\/.+\/subscription_state\?,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/TextNow/State.js,script-update-interval=-1

settings = type=http-response,pattern=^https:\/\/api\.textnow\.me\/.+\/settings\?,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/TextNow/Setting.js,script-update-interval=-1

TextNow = type=http-response,pattern=^https:\/\/api\.textnow\.me\/.+\/users\/.+\?client_id,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/TextNow/TextNow.js,script-update-interval=-1

# > 轻颜相机 & ulike & 蒸汽波相机(vaporcam)三合一 解锁VIP(By @s y & Alex0510)
轻颜相机 = type=http-response,pattern=^https?:\/\/commerce-.*api\.faceu\.mobi\/commerce\/v1\/subscription\/user_info,requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Photo/ULike.js,script-update-interval=-1

# > Unlock Documents-PdfExpert-Scaner Pro
Documents-PdfExpert = type=http-response,pattern=^https?:\/\/license\.pdfexpert\.com\/api\/.+\/subscription\/(refresh$|check$),requires-body=1,max-size=0,script-path=https://hub.nange.cn/Script/Readdle/PDFExpert.js,script-update-interval=-1

# > 简书
简书1 = type=http-request,pattern=^https?:\/\/links\.jianshu\.com\/go\?to=,script-path=https://hub.nange.cn/Script/Others/NoRedirect.js
简书2 = type=http-request,pattern=^https?:\/\/www\.jianshu\.com\/go-wild\?ac=\d&url=,script-path=https://hub.nange.cn/Script/Others/NoRedirect.js

# > 知乎
知乎 = type=http-request,pattern=^https?:\/\/link\.zhihu\.com\/\?target=,script-path=https://hub.nange.cn/Script/Others/NoRedirect.js

# > 微博
微博1 = type=http-request,pattern=^https?:\/\/weibo\.cn\/sinaurl\?(.*&)?(u|toasturl|goto)=,script-path=https://hub.nange.cn/Script/Others/NoRedirect.js

微博2 = type=http-request,pattern=^https?:\/\/shop\.sc\.weibo\.com\/h5\/jump\/error\?(.*&)?url=(.*),script-path=https://hub.nange.cn/Script/Others/NoRedirect.js

微博3 = type=http-response,pattern=^https?:\/\/(sinaurl|t)\.cn\/,script-path=https://hub.nange.cn/Script/Others/NoRedirect.js

# > DY
DY = type=http-response,pattern=^https?:\/\/.+?\.(my10api|(.*91.*))\.(com|tips|app|xyz)(:\d{2,5}|)\/api.php$,script-path=https://hub.nange.cn/Script/Live/DY.js

# > Ban
Ban = type=http-response,pattern=^https?:\/\/.+?\.(guoguo|pipi|fuli|xiang(jiao|xiang))apps\.com\/(ucp\/index|getGlobalData|index|(\/|)vod\/reqplay\/),script-path=https://hub.nange.cn/Script/Live/Ban.js

[MITM]
hostname = %APPEND% x.io, -*vmgirls.com, -*nange.cn, -*nan.ge, -*bk9.net, -*cdn.ink, -*nangle.com.cn, -*cloudimg.net, api.royalapps.com, *.miguvideo.com, *poco.cn, api.rr.tv, ios.prod.ftl.netflix.com, link.zhihu.com, vsco.co, api.revenuecat.com, ap*.intsig.net, lcs-mobile-cops.adobe.io, photos.adobe.io, -buy.itunes.apple.com, billing.peakcloud.org, api.textnow.me, commerce-.*api.faceu.mobi, commerce-api.faceu.mobi, pay.wecut.com, license.pdfexpert.com, links.jianshu.com, www.jianshu.com, weibo.cn, sinaurl.cn, home.115.com, shop.sc.weibo.com, ios.fuliapps.com, apple.fuliapps.com, ios.xiangjiaoapps.com, apple.xiangjiaoapps.com, *.xiangxiangapps.com, *.pipiapps.com, *.guoguoapps.com
