#!name=常用规则
#!desc=日用夜用

[General]
# > 优酷去广告
force-http-engine-hosts = %APPEND% *.cp31.ott.cibntv.net

[Host]
# > Apple下载解析加速
*.itunes.apple.com = script:DNSPod

[Rule]
# > 网易云音乐
URL-REGEX,^https:\/\/interface\.music\.163\.com\/eapi\/usertool\/,DIRECT
URL-REGEX,^https:\/\/music\.163\.com\/user\/,DIRECT
URL-REGEX,^https:\/\/music\.163\.com\/#\/user\/,DIRECT
URL-REGEX,^https:\/\/interface\.music\.163\.com\/weapi\/activity\/bonus\/playpage\/,DIRECT
URL-REGEX,^https:\/\/interface\.music\.163\.com\/weapi\/resource-exposure\/,DIRECT
URL-REGEX,^https:\/\/music\.163\.com\/api\/music-vip-membership\/,DIRECT
URL-REGEX,^https:\/\/music\.163\.com\/weapi\/user\/,DIRECT
URL-REGEX,^https:\/\/music\.163\.com\/store\/,DIRECT

# > 京东，去启动广告
URL-REGEX,^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=start$,REJECT-TINYGIF

# > 哔哩哔哩 去广告 
URL-REGEX,https://app.bilibili.com/x/v2/(splash|search/(defaultword|square)),REJECT
URL-REGEX,https://api.bilibili.com/x/v2/dm/ad,REJECT

# > YouTube 去片头广告
URL-REGEX,^https:\/\/.+\.googlevideo\.com\/.+&oad,REJECT

# > 知乎 去广告
# >> SOME MCN INFO MAY BE USEFUL
# URL-REGEX,https://www.zhihu.com/api/v4/mcn/,REJECT
DOMAIN,appcloud2.zhihu.com,REJECT

# >> DO NOT GET CDN-BASED IP
DOMAIN,118.89.204.198,REJECT

USER-AGENT,AVOS*,REJECT
URL-REGEX,https://api.zhihu.com/(ad|drama|fringe|commercial|market/popover|search/(top|preset|tab)|.*featured-comment-ad),REJECT
AND,((USER-AGENT,ZhihuHybrid*), (URL-REGEX,.*recommend)),REJECT

# > 优酷 去广告
URL-REGEX,^http:\/\/.*\.cp31\.ott\.cibntv\.net\/youku\/,REJECT-TINYGIF

# > 人人视频 去广告
AND,((USER-AGENT,PUClient*), (NOT,((DOMAIN-SUFFIX,rr.tv)))),REJECT
URL-REGEX,^https?:\/\/api\.rr\.tv\/(?:ad\/getAll$|storage/business/rootName/app/homePage),REJECT

[Header Rewrite]
# > 颇可
^https?:\/\/[\w-]+\.(poco|pocoimg)\.cn header-replace User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87 Version/11.1.1 Safari/605.1.15

# > 添加标记
;^https?://(?:\w+\.)*?((nan|cdn|nange|bk9|nangle|vmgirls|cloudimg|somecache|applecache)\.(?:com\.cn|cn|ink|ge|com|net))[\\\/]* header-add Visitor Surge

# > 更改 UA
;^https?://(?:\w+\.)*?((nan|cdn|nange|bk9|nangle|vmgirls|cloudimg|somecache|applecache)\.(?:com\.cn|cn|ink|ge|com|net))[\\\/]* header-replace User-Agent Surge

[URL Rewrite]
# > TikTok 解锁
(?<=_region=)CN(?=&) KR 307
(?<=&mcc_mnc=)4 2 307
    ^(https?:\/\/(tnc|dm)[\w-]+\.\w+\.com\/.+)(\?)(.+) $1$3 302
(^https?:\/\/*\.\w{4}okv.com\/.+&.+)(\d{2}\.3\.\d)(.+) $118.0$3 302

# > 知乎
^https:\/\/link\.zhihu\.com\/\?target=(https?)?(%3A|:)?(\/\/|%2F%2F)?(.*?)(&source.*)?$ http://$4 302
# > 115
^https?:\/\/home\.115\.com\/go\?(https?:\/\/)?(.*) http://$2 302

# > YouTube
ctier=[A-Z] citer=A 302

# > 人人视频 解锁AI原画 (by@george Jiang & R)
人人影视 = requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Live/RRTV.js,type=http-response,pattern=^https:\/\/api\.rr\.tv(\/user\/privilege\/list|\/ad\/getAll|\/rrtv-video\/v4plus\/season\/detail)

# > 抖音去广告和水印
^https://aweme-eagle(.*)\.snssdk\.com/aweme/v2/ https://aweme-eagle$1.snssdk.com/aweme/v1/ 302
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/feed\/ https://aweme.snssdk.com/aweme/v1/feed/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/aweme\/post\/ https://aweme.snssdk.com/aweme/v1/aweme/post/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/follow\/feed\/ https://aweme.snssdk.com/aweme/v1/follow/feed/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/nearby\/feed\/ https://aweme.snssdk.com/aweme/v1/nearby/feed/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/search\/item\/ https://aweme.snssdk.com/aweme/v1/search/item/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/general\/search\/single\/ https://aweme.snssdk.com/aweme/v1/general/search/single/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/hot/search\/video\/list\/ https://aweme.snssdk.com/aweme/v1/hot/search/video/list/ header

[Script]
# > Apple下载解析加速
DNSPod = type=dns,script-path=https://hub.nan.ge/Surge/Script/DNS/DNSPod.js,script-update-interval=-1

# > TestFlight解除下载限制
TF下载修正 = type=http-request,pattern=^https?:\/\/testflight\.apple\.com\/v\d\/accounts\/.+?\/install$,requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Apple/TestFlight.js

# > 该模块可解决iOS14或IPadOS14无法在移动端安装IPA的问题. 注: 需要使用Shu+捷径或Jsbox辅助安装.
IPA应用安装 = type=http-request,pattern=^https:\/\/x.io/(install|download)(\/jsbox)?$,requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Apple/iPA_Install.js

# > BoxJS
BoxJs = type=http-request,pattern=^https?://boxjs.com(/api|/home|/sub|/my|/app|/log|/revert)?($|\/),script-path=https://hub.nan.ge/Surge/Script/Others/BoxJS.js, requires-body=true, timeout=120

# > 人人视频 去广告
rrsp_video = type=http-response,requires-body=true,pattern=^https?:\/\/api\.rr\.tv\/watch\/v\d\/get_movie_info,script-path=https://hub.nan.ge/Surge/Script/Live/RRTVAds.js
rrsp_banner = type=http-response,requires-body=true,pattern=^https?:\/\/api\.rr\.tv\/v\dplus\/index\/channel,script-path=https://hub.nan.ge/Surge/Script/Live/RRTVAds.js

# > 奈飞评分
奈飞评分 = script-path=https://hub.nan.ge/Surge/Script/Netflix/Rating.js,type=http-request,pattern=^https?://ios\.prod\.ftl\.netflix\.com/iosui/user/.+path=%5B%22videos%22%2C%\d+%22%2C%22summary%22%5D
奈飞评分 = requires-body=1,script-path=https://hub.nan.ge/Surge/Script/Netflix/Rating.js,type=http-response,pattern=^https?://ios\.prod\.ftl\.netflix\.com/iosui/user/.+path=%5B%22videos%22%2C%\d+%22%2C%22summary%22%5D
单集评分 = type=http-response,pattern=^https?://ios\.prod\.ftl\.netflix\.com/iosui/warmer/.+type=show-ath,requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Netflix/RatingSeason.js

# > 抖音去广告和水印
抖音 & TikTok = type=http-request,pattern=^https:\/\/.*\.(amemv|musical)\.(com|ly)\/aweme\/v.*\/(feed|post),requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/ByteDance/Aweme.js
抖音 & TikTok = type=http-response,pattern=^https:\/\/.*\.(amemv|musical)\.(com|ly)\/aweme\/v.*\/(feed|post),requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/ByteDance/Aweme.js
;抖音 = type=http-response,requires-body=1,max-size=-1,pattern=^https?:\/\/aweme\.snssdk\.com\/aweme\/v1\/(feed|aweme\/post|follow\/feed|nearby\/feed|search\/item|general\/search\/single|hot\/search\/video\/list)\/,script-path=https://hub.nan.ge/Surge/Script/ByteDance/DouYin.js

# > 微博去广告
开屏 = requires-body=1,script-path=https://hub.nan.ge/Surge/Script/Weibo/LaunchAds.js,type=http-response,pattern=^https?://(sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad.php|/wbapplua/wbpullad.lua)
时间轴 = type=http-response,requires-body=1,max-size=-1,pattern=^https?://m?api\.weibo\.c(n|om)/2/(statuses/(unread|extend|positives/get|(friends|video)(/|_)(mix)?timeline)|stories/(video_stream|home_list)|(groups|fangle)/timeline|profile/statuses|comments/build_comments|photo/recommend_list|service/picfeed|searchall|cardlist|page|!/photos/pic_recommend_status|video/tiny_stream_video_list),script-path=https://hub.nan.ge/Surge/Script/Weibo/Timeline.js

# > 微信公众号
WeChat = script-path=https://hub.nan.ge/Surge/Script/WeChat/WeChat.js,type=http-request,pattern=^https://mp\.weixin\.qq\.com/mp/getappmsgad

# > 知乎 去广告
People = type=http-response,requires-body=1,max-size=0,pattern=https://api.zhihu.com/people/,script-path=https://hub.nan.ge/Surge/Script/Zhihu/People.js
Feed = type=http-response,requires-body=1,max-size=0,pattern=https://api.zhihu.com/moments/recommend,script-path=https://hub.nan.ge/Surge/Script/Zhihu/Feed.js
Recommend = type=http-response,requires-body=1,max-size=0,pattern=https://api.zhihu.com/topstory/recommend,script-path=https://hub.nan.ge/Surge/Script/Zhihu/Recommend.js
Answer = type=http-response,requires-body=1,max-size=0,pattern=https://api.zhihu.com/v4/questions,script-path=https://hub.nan.ge/Surge/Script/Zhihu/Answer.js

# > VSCO滤镜VIP
VSCO = requires-body=1,script-path=https://hub.nan.ge/Surge/Script/Photo/VSCO.js,type=http-response,pattern=^https?:\/\/vsco\.co\/api\/subscriptions\/2.1\/user-subscriptions\/

# > 91短视频
 91短视频 = requires-body=1,script-path=https://hub.nan.ge/Surge/Script/Live/MicroVideo.js,type=http-response,pattern="^https?:\/\/.+\.(my10api|(.*91.*))\.(com|tips|app|xyz)(:\d{2,5})?\/api.php$"

http-response ^https?:\/\/.+\.(my10api|(.*91.*))\.(com|tips|app|xyz)(:\d{2,5})?\/api.php$ requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Live/ShortVideo.js

# > 香蕉视频VIP
BananaVideo = requires-body=1,script-path=https://hub.nan.ge/Surge/Script/Live/BananaVideo.js,type=http-response,pattern=^https?:\/\/.*\.(lago|fuli|xiang(jiao|xiang))apps\.com\/(ucp\/index|getGlobalData|.+\/reqplay\/)

# Termius 解锁本地pro  (By Maasea)
;Termius = requires-body=1,script-path=https://hub.nan.ge/Surge/Script/Dev/Termius.js,type=http-response,pattern=https:\/\/api\.termius\.com\/api\/v3\/bulk\/account\/

# > WPS (By eHpo1)
WPS = requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Work/WPS.js,type=http-response,pattern=^https://account.wps.*/api/users/

# > WorkingCopy.js
;WorkingCopy= requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Dev/WorkingCopy.js,script-update-interval=0,type=http-response,pattern=^https:\/\/education\.github\.com\/api\/user$

# > Lightroom
Adobe Lightroom = type=http-response,pattern=^https:\/\/photos\.adobe\.io\/v2\/accounts,requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Adobe/Lightroom.js,script-update-interval=0

# > Photoshop Express
Photoshop Express = type=http-response,pattern=^https:\/\/lcs-mobile-cops\.adobe\.io\/mobile_profile,requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Adobe/PhotoShopExpress.js,script-update-interval=0

# > CamScanner unlocks pro, Cloud scanning is not available.
CamScanner = type=http-response,pattern=https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\?,requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Work/CamScanner.js,script-update-interval=0

# > Fantastical 内购解锁 (By @sunshy)
Fantastical = requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Work/Fantastical.js,type=http-response,pattern=^https:\/\/api\.flexibits\.com\/v1\/(auth|account)\/(device|details|appstore-receipt)\/$

# > Bear熊掌记 (By Miao Miao)
Bear 熊掌记 = requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Work/Bear.js,type=http-response,pattern=^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt

# > XMind思维导图
XMind = requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Work/XMind.js,type=http-response,pattern=https:\/\/www\.xmind\.cn\/\_res\/devices

# > 智能证件照相机 (by @superuv)
证件照相机 = requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Work/TakeIDPhoto.js,type=http-response,pattern=^https:\/\/app\.xunjiepdf\.com\/api\/v4\/virtualactregister

# > GK扫描仪(by @superuv)
扫描仪 = requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Work/GKScaner.js,type=http-response,pattern=^https:\/\/api\.gkocr\.com\/api\/userlogin1.php

# > Buyhack
VerifyReceipt = requires-body=1,max-size=262144,script-path=https://hub.nan.ge/Surge/Script/Live/VerifyReceipt.js,script-update-interval=0,type=http-response,pattern=^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt$

# > Draft
Draft = requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Work/Draft.js,script-update-interval=0,type=http-response,pattern=^https:\/\/backend\.getdrafts\.com\/api\/.*\/verification

# > DayOne
# >> 1.启用本脚本与 Pre 脚本
# >> 2.重启 DayOne，稍等片刻等待高级版出现
# >> 3.禁用掉 Pre 脚本，重启 DayOne，确认高级版状况不变
# >> Pre_DayOne
; DayOnePre = debug=1,script-path=https://hub.nan.ge/Surge/Script/DayOne/DayOnePre.js,type=http-request,pattern=^https:\/\/dayone\.me\/api\/users$
dayone.surge = requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/DayOne/DayOne.js,script-update-interval=0,type=http-response,pattern=^https:\/\/dayone\.me\/api\/(users|v2\/users\/(account-status|receipt))$

# > Peak 解锁Pro
Peak = requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Work/Peak.js,type=http-response,pattern=^https:\/\/billing\.peakcloud\.org\/billing\/2\/user\/me?

# > 菜谱大全解锁vip (By @photonmang)
菜谱大全 = requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/Live/CookBook.js,type=http-response,pattern=https?:\/\/api\.jiaonizuocai\.com

# > Gyroscope 解锁 pro (By Maasea)
GyroScope = requires-body=1,script-path=https://hub.nan.ge/Surge/Script/Work/GyroScope.js,type=http-response,pattern=^https:\/\/api\.gyrosco\.pe\/v1\/account\/$

# > TextNow
Textnow = type=http-response,pattern=^https:\/\/api\.textnow\.me\/api2.0\/users\/.+,requires-body=1,max-size=0,script-path=https://hub.nan.ge/Surge/Script/TextNow/TextNow.js,script-update-interval=0

# > 简书
简书1 = type=http-request,pattern=^https:\/\/links\.jianshu\.com\/go\?to=,script-path=https://hub.nan.ge/Surge/Script/Others/NoRedirect.js
简书2 = type=http-request,pattern=^https:\/\/www\.jianshu\.com\/go-wild\?ac=\d&url=,script-path=https://hub.nan.ge/Surge/Script/Others/NoRedirect.js

# > 知乎
知乎 = type=http-request,pattern=^https:\/\/link\.zhihu\.com\/\?target=,script-path=https://hub.nan.ge/Surge/Script/Others/NoRedirect.js

# > 微博
微博1 = type=http-request,pattern=^https?:\/\/weibo\.cn\/sinaurl\?(.*&)?(u|toasturl|goto)=,script-path=https://hub.nan.ge/Surge/Script/Others/NoRedirect.js
微博2 = type=http-request,pattern=^https:\/\/shop\.sc\.weibo\.com\/h5\/jump\/error\?(.*&)?url=(.*),script-path=https://hub.nan.ge/Surge/Script/Others/NoRedirect.js
微博3 = type=http-response,pattern=^https?:\/\/(sinaurl|t)\.cn\/,script-path=https://hub.nan.ge/Surge/Script/Others/NoRedirect.js


[MITM]
hostname = %APPEND% x.io, -*vmgirls.com, -  *nange.cn, -*nan.ge, -*bk9.net, -*cdn.ink, -*nangle.com.cn, -*cloudimg.net, -*somecache.com, -*applecache.com, *poco.cn, *pocoimg.cn, api.rr.tv, 6.6.6.6, 2.2.2.2, *.googlevideo.com, ios.prod.ftl.netflix.com, api.weibo.cn, mapi.weibo.com, *.uve.weibo.com, mp.weixin.qq.com, www.zhihu.com, api.zhihu.com, link.zhihu.com, 118.89.204.198, *.tiktokv.com, *.byteoversea.com, *.tik-tokapi.com, ios.fuliapps.com, vsco.co, apple.fuliapps.com, *.lagoapps.com, account.wps.*, ios.xiangjiaoapps.com, apple.xiangjiaoapps.com, *.xiangxiangapps.com, ap*.intsig.net, lcs-mobile-cops.adobe.io, photos.adobe.io, -buy.itunes.apple.com, api.flexibits.com, www.xmind.cn, app.xunjiepdf.com, api.gkocr.com, api.jiaonizuocai.com, api.gyrosco.pe, backend.getdrafts.com, dayone.me, billing.peakcloud.org, api.textnow.me, links.jianshu.com, www.jianshu.com, weibo.cn, sinaurl.cn, home.115.com, shop.sc.weibo.com, testflight.apple.com, *music.163.com
