#!name= 微博广告
#!desc=移除微博 App 启动页广告和推荐页广告。
#!system=ios

[Script]
# > 微博去广告
开屏 = requires-body=1,script-path=https://hub.nan.ge/Script/Weibo/Launch.js,type=http-response,pattern=^https?://(sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad.php|/wbapplua/wbpullad.lua)

微博 = type=http-response,requires-body=1,max-size=-1,pattern=^https?://m?api\.weibo\.c(n|om)/2/(statuses/(unread|extend|positives/get|(friends|video)(/|_)(mix)?timeline)|stories/(video_stream|home_list)|(groups|fangle)/timeline|profile/statuses|comments/build_comments|photo/recommend_list|service/picfeed|searchall|cardlist|page|!/(photos/pic_recommend_status|live/media_homelist)|video/tiny_stream_video_list|photo/info|remind/unread_count),script-path=https://hub.nan.ge/Script/Weibo/Timeline.js

启动 = requires-body=1,script-path=https://hub.nan.ge/Script/Weibo/SdkAd.js,type=http-response,pattern=^https?://(sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad.php|/wbapplua/wbpullad.lua)

个人主页 = type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)/2\/profile\/me\?,requires-body=1,max-size=0,script-path=https://hub.nan.ge/Script/Weibo/Profile.js

评论 = type=http-response,pattern=^https?://m?api\.weibo\.c(n|om)/2/comments/build_comments\?, requires-body=1,max-size=0,script-path=https://hub.nan.ge/Script/Weibo/Comment.js

最新推荐 = type=http-response,pattern=^https?://m?api\.weibo\.c(n|om)/2/(statuses/unread_hot_timeline|statuses/friends/timeline|video/tiny_stream_video_list|statuses/unread_friends_timeline)\?, requires-body=1,max-size=0,script-path=https://hub.nan.ge/Script/Weibo/Status.js

超话搜索 = type=http-response,pattern=^https?://m?api\.weibo\.c(n|om)/2/(searchall|page)\?, requires-body=1,max-size=0,script-path=https://hub.nan.ge/Script/Weibo/CardList.js

发现热门 = type=http-response,pattern=^https?://m?api\.weibo\.c(n|om)/2/cardlist\?, requires-body=1,max-size=0,script-path=https://hub.nan.ge/Script/Weibo/FindHot.js

创作者广告共享计划 = type=http-response,pattern=^https://m?api\.weibo\.c(n|om)/2/statuses/extend\?, requires-body=1,max-size=0,script-path=https://hub.nan.ge/Script/Weibo/Status_Extend.js

[MITM]
hostname = %APPEND% *.uve.weibo.com, api.weibo.cn, api.weibo.com, mapi.weibo.com, mapi.weibo.cn
