name: AdRules

on:
  push:
    branches:
      - "Her"
    paths-ignore:
      - "LICENSE"
      - "*.md"
      - "**/*.md"
      - ".*"
      - "node_modules"
  schedule:
    - cron:  0 */6 * * *

jobs:
  Update:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14]

    steps:
      - name: Fetch repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: yarn install, update
        run: |
          yarn install
          yarn update-rules
        
      - name: Merge and Rules and remove duplicates
        run: |
          curl -LR -o Surge/DomainSet/AdRules/anti-ad.txt "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt"
          awk 'FNR==1{print ""}{print}' Surge/DomainSet/AdRules/*.list > Surge/DomainSet/AdRules/merge.txt
          awk '!seen[$0]++' Surge/DomainSet/AdRules/merge.txt > Surge/DomainSet/AdRules/merge.list
          sed '/^$/d' Surge/DomainSet/AdRules/merge.list > Surge/DomainSet/AdRules/AdRules.list
          mv Surge/DomainSet/AdRules/AdRules.list Surge/DomainSet/AdRules.list
          rm -rf Surge/DomainSet/AdRules/merge.txt
          rm -rf Surge/DomainSet/AdRules/merge.list
          rm -rf Surge/DomainSet/AdRules/anti-ad.txt

      - name: commit, push
        uses: EndBug/add-and-commit@v5
        with:
          add: "-A"
          author_name: 佩佩
          author_email: admin@nange.cn
          message: "Update AdRules"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}