name: AdRules

on:
  workflow_dispatch:
  push:
    branches:
      - "Her"
    paths-ignore:
      - "LICENSE"
      - "*.md"
      - "**/*.md"
      - ".*"
      - "node_modules"
  schedule:
    - cron:  0 */24 * * *

jobs:
  Update:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14]

    steps:
      - name: Fetch repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: yarn install, update
        run: |
          yarn install
          yarn update-adrules
        
      - name: Merge and Rules and remove duplicates
        run: |
          curl -LR -o Surge/RuleSet/AdRules/anti-ad.txt "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt"
          curl -LR -o Surge/RuleSet/AdRules/uBlack.list "https://raw.githubusercontent.com/dallaslu/penzai-list/main/Surge.txt"
          awk 'FNR==1{print ""}{print}' Surge/RuleSet/AdRules/*.list > Surge/RuleSet/AdRules/Merge.txt
          awk '!seen[$0]++' Surge/RuleSet/AdRules/Merge.txt > Surge/RuleSet/AdRules/Merge.list
          sed '/^$/d' Surge/RuleSet/AdRules/Merge.list > Surge/RuleSet/AdRule.list
          rm -rf Surge/RuleSet/AdRules/Merge.txt
          rm -rf Surge/RuleSet/AdRules/Merge.list

      - name: Download ChinaIPs.list
        run: |
          curl -LR -o Surge/RuleSet/ChinaIPs.txt "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaIPs/ChinaIPs.list"
          awk 'FNR==1{print ""}{print}' Surge/RuleSet/ChinaIPs.txt | grep -v "#" | sed '/^$/d' > Surge/RuleSet/ChinaIPs.list
          rm -rf Surge/RuleSet/ChinaIPs.txt

      - name: commit, push
        uses: EndBug/add-and-commit@v5
        with:
          add: "-A"
          author_name: 佩佩
          author_email: admin@nange.cn
          message: "Update AdRules"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}