name: Update Country.mmdb

on:
  workflow_dispatch:
  push:
    branches:
      - "Her"
    paths-ignore:
      - "LICENSE"
      - "*.md"
      - "**/*.md"
      - ".*"
      - "node_modules"
  #schedule:
  #  - cron: 0 */24 * * *
jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3

    - name: Get Country.mmdb
      run: |
        cd $GITHUB_WORKSPACE
        cd GeoIP
        wget -N --no-check-certificate https://raw.githubusercontent.com/xOS/GeoIPs/release/Country.mmdb
        wget -N --no-check-certificate https://raw.githubusercontent.com/xOS/Country.mmdb/release/Country-lite.mmdb
        wget -N --no-check-certificate https://raw.githubusercontent.com/xOS/GeoIPs/release/Country-only-cn-private.mmdb
    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.5.0
      with:
        author_name: 翠花
        author_email: admin@nange.cn
        message: "Update Country.mmdb"
        add: "-A"
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
