name: Update China.mmdb

on:
  push:
    branches:
      - "Her"
    paths-ignore:
      - "LICENSE"
      - "*.md"
      - ".*"
  schedule:
    - cron: 0 */6 * * *
jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3

    - name: Get China.mmdb
      run: |
        cd $GITHUB_WORKSPACE
        mkdir GEOIP
        cd GEOIP
        wget -N --no-check-certificate https://raw.githubusercontent.com/XOS/China.mmdb/release/cn-ip-cidr.txt
        wget -N --no-check-certificate https://raw.githubusercontent.com/XOS/China.mmdb/release/China.list
        wget -N --no-check-certificate https://raw.githubusercontent.com/XOS/China.mmdb/release/China.mmdb
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.4.0
      with:
        author_name: 翠花
        author_email: admin@nange.cn
        message: "Add China.mmdb"
        add: "-A"
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
